create extension if not exists pg_cron with schema extensions;
create extension if not exists pg_net with schema extensions;

create table if not exists public.f1_sessions_cache (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  session_key bigint,
  meeting_key bigint,
  session_name text not null,
  session_type text,
  meeting_name text,
  location text,
  date_start timestamptz not null,
  date_end timestamptz,
  season_year integer not null,
  source_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists f1_sessions_cache_session_key_idx
  on public.f1_sessions_cache (session_key)
  where session_key is not null;

create index if not exists f1_sessions_cache_meeting_key_idx
  on public.f1_sessions_cache (meeting_key);

create index if not exists f1_sessions_cache_date_start_idx
  on public.f1_sessions_cache (date_start);

create table if not exists public.notification_queue (
  id bigint generated by default as identity primary key,
  notification_type text not null check (
    notification_type in ('weekly_digest', 'session_reminder', 'post_race_briefing')
  ),
  dedupe_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz not null,
  status text not null default 'pending' check (
    status in ('pending', 'processing', 'sent', 'failed')
  ),
  retry_count integer not null default 0 check (retry_count >= 0),
  last_error text,
  locked_at timestamptz,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists notification_queue_status_scheduled_for_idx
  on public.notification_queue (status, scheduled_for);

create index if not exists notification_queue_locked_at_idx
  on public.notification_queue (locked_at);

create table if not exists public.delivery_logs (
  id bigint generated by default as identity primary key,
  queue_id bigint not null references public.notification_queue (id) on delete cascade,
  user_id bigint not null references public.users (user_id) on delete cascade,
  attempt integer not null check (attempt >= 1),
  status text not null check (status in ('dry_run', 'sent', 'failed', 'skipped')),
  provider text not null,
  provider_message_id text,
  error_message text,
  created_at timestamptz not null default now()
);

create index if not exists delivery_logs_queue_id_idx
  on public.delivery_logs (queue_id, created_at desc);

create index if not exists delivery_logs_queue_id_user_id_status_idx
  on public.delivery_logs (queue_id, user_id, status);

alter table public.f1_sessions_cache enable row level security;
alter table public.notification_queue enable row level security;
alter table public.delivery_logs enable row level security;

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_f1_sessions_cache_updated_at on public.f1_sessions_cache;
create trigger set_f1_sessions_cache_updated_at
before update on public.f1_sessions_cache
for each row
execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_notification_queue_updated_at on public.notification_queue;
create trigger set_notification_queue_updated_at
before update on public.notification_queue
for each row
execute function public.set_current_timestamp_updated_at();

create or replace function public.upsert_notification_queue_item(
  input_notification_type text,
  input_dedupe_key text,
  input_payload jsonb,
  input_scheduled_for timestamptz
)
returns public.notification_queue
language plpgsql
security definer
set search_path = public
as $$
declare
  resulting_row public.notification_queue;
begin
  insert into public.notification_queue (
    notification_type,
    dedupe_key,
    payload,
    scheduled_for
  )
  values (
    input_notification_type,
    input_dedupe_key,
    input_payload,
    input_scheduled_for
  )
  on conflict (dedupe_key) do update
  set notification_type = excluded.notification_type,
      payload = excluded.payload,
      scheduled_for = excluded.scheduled_for,
      status = case
        when public.notification_queue.status = 'sent' then public.notification_queue.status
        else 'pending'
      end,
      retry_count = case
        when public.notification_queue.status = 'sent' then public.notification_queue.retry_count
        else 0
      end,
      last_error = case
        when public.notification_queue.status = 'sent' then public.notification_queue.last_error
        else null
      end,
      locked_at = case
        when public.notification_queue.status = 'sent' then public.notification_queue.locked_at
        else null
      end,
      sent_at = case
        when public.notification_queue.status = 'sent' then public.notification_queue.sent_at
        else null
      end,
      updated_at = now()
  returning * into resulting_row;

  return resulting_row;
end;
$$;

revoke all on function public.upsert_notification_queue_item(text, text, jsonb, timestamptz)
  from public;
revoke all on function public.upsert_notification_queue_item(text, text, jsonb, timestamptz)
  from anon;
revoke all on function public.upsert_notification_queue_item(text, text, jsonb, timestamptz)
  from authenticated;
grant execute on function public.upsert_notification_queue_item(text, text, jsonb, timestamptz)
  to service_role;

create or replace function public.claim_notification_queue_items(batch_size integer default 25)
returns setof public.notification_queue
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  with candidates as (
    select queue.id
    from public.notification_queue as queue
    where queue.status = 'pending'
      and queue.scheduled_for <= now()
      and (
        queue.locked_at is null
        or queue.locked_at < now() - interval '15 minutes'
      )
    order by queue.scheduled_for asc, queue.id asc
    for update skip locked
    limit greatest(batch_size, 1)
  ),
  claimed as (
    update public.notification_queue as queue
    set status = 'processing',
        locked_at = now(),
        updated_at = now()
    where queue.id in (select id from candidates)
    returning queue.*
  )
  select *
  from claimed
  order by scheduled_for asc, id asc;
end;
$$;

revoke all on function public.claim_notification_queue_items(integer) from public;
revoke all on function public.claim_notification_queue_items(integer) from anon;
revoke all on function public.claim_notification_queue_items(integer) from authenticated;
grant execute on function public.claim_notification_queue_items(integer) to service_role;

create or replace function public.unschedule_notification_v2_jobs()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_job record;
begin
  for current_job in
    select jobid
    from cron.job
    where jobname in ('fn-planner-v2-weekly', 'fn-dispatcher-v2-minute')
  loop
    perform cron.unschedule(current_job.jobid);
  end loop;
end;
$$;

create or replace function public.schedule_notification_v2_jobs(
  project_url_secret_name text default 'project_url',
  edge_secret_name text default 'secret_token',
  planner_schedule text default '0 6 * * 1',
  dispatcher_schedule text default '* * * * *'
)
returns table (planner_job_id bigint, dispatcher_job_id bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  project_url text;
  edge_secret text;
begin
  select decrypted_secret into project_url
  from vault.decrypted_secrets
  where name = project_url_secret_name;

  select decrypted_secret into edge_secret
  from vault.decrypted_secrets
  where name = edge_secret_name;

  if project_url is null or edge_secret is null then
    raise exception 'Missing project_url or secret_token secret in Vault.';
  end if;

  perform public.unschedule_notification_v2_jobs();

  planner_job_id := cron.schedule(
    'fn-planner-v2-weekly',
    planner_schedule,
    format(
      $job$
      select net.http_post(
        url := %L,
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', %L
        ),
        body := '{"mode":"weekly"}'::jsonb
      );
      $job$,
      project_url || '/functions/v1/fn-planner-v2',
      'Bearer ' || edge_secret
    )
  );

  dispatcher_job_id := cron.schedule(
    'fn-dispatcher-v2-minute',
    dispatcher_schedule,
    format(
      $job$
      select net.http_post(
        url := %L,
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'Authorization', %L
        ),
        body := '{}'::jsonb
      );
      $job$,
      project_url || '/functions/v1/fn-dispatcher-v2',
      'Bearer ' || edge_secret
    )
  );

  return next;
end;
$$;

revoke all on function public.schedule_notification_v2_jobs(text, text, text, text) from public;
revoke all on function public.schedule_notification_v2_jobs(text, text, text, text) from anon;
revoke all on function public.schedule_notification_v2_jobs(text, text, text, text) from authenticated;
grant execute on function public.schedule_notification_v2_jobs(text, text, text, text)
  to service_role;

revoke all on function public.unschedule_notification_v2_jobs() from public;
revoke all on function public.unschedule_notification_v2_jobs() from anon;
revoke all on function public.unschedule_notification_v2_jobs() from authenticated;
grant execute on function public.unschedule_notification_v2_jobs() to service_role;
