create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (user_id) on delete cascade,
  notification_key text not null,
  sent_at timestamptz not null default now()
);

create unique index if not exists notification_deliveries_user_id_notification_key_idx
  on public.notification_deliveries (user_id, notification_key);
